apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - image: rrucdocker2020/sre_api:2
          ports:
            - containerPort: 8001
          name: sre-api
          resources:
            requests:
              cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: nodejs-app
spec:
  selector:
    app: nodejs-app
  type: LoadBalancer
  ports:
    - nodePort: 30002
      port: 80
      targetPort: 8001
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
