apiVersion: v1
kind: Pod
metadata:
  name: nodejs-pod
  labels:
    app: nodejs-app
spec:
  containers:
    - image: sre_demo_api_service
      ports:
        - containerPort: 8001
      name: sre-demo-api
      imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: nodejs-app
spec:
  selector:
    app: nodejs-app
  type: NodePort
  ports:
    - nodePort: 30001
      port: 80
      targetPort: 8001
